<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Core/**/*.cs;Executors/**/*.cs;Parser/**/*.cs;Storage/**/*.cs" />
    <ProjectReference Include="Core\Engine.Core.csproj" />
    <ProjectReference Include="Parser\Engine.Parser.csproj" />
    <ProjectReference Include="Executors\Engine.Executors.csproj" />
    <ProjectReference Include="Storage\Engine.Storage.csproj" />
  </ItemGroup>

</Project>
