CREATE TABLE customers (id INTEGER, name TEXT, city TEXT);
INSERT INTO customers VALUES (1, 'Avery Stone', 'Portland');
INSERT INTO customers VALUES (2, 'Morgan Reed', 'Austin');
INSERT INTO customers VALUES (3, 'Jordan Blake', 'Denver');
INSERT INTO customers VALUES (4, 'Riley Quinn', 'Boston');
INSERT INTO customers VALUES (5, 'Casey Lane', 'Seattle');
INSERT INTO customers VALUES (6, 'Taylor Gray', 'Phoenix');
INSERT INTO customers VALUES (7, 'Cameron West', 'Chicago');
INSERT INTO customers VALUES (8, 'Drew Ellis', 'Miami');
INSERT INTO customers VALUES (9, 'Parker James', 'Atlanta');
INSERT INTO customers VALUES (10, 'Hayden Brooks', 'Detroit');
INSERT INTO customers VALUES (11, 'Emerson Cole', 'Madison');
INSERT INTO customers VALUES (12, 'Finley Hart', 'Raleigh');
INSERT INTO customers VALUES (13, 'Rowan Miles', 'Salem');
INSERT INTO customers VALUES (14, 'Skyler Ford', 'Boise');
INSERT INTO customers VALUES (15, 'Dakota Wells', 'Tucson');
INSERT INTO customers VALUES (16, 'Reese Palmer', 'Albany');
INSERT INTO customers VALUES (17, 'Kendall Price', 'Boulder');
INSERT INTO customers VALUES (18, 'Robin Hayes', 'Buffalo');
INSERT INTO customers VALUES (19, 'Shiloh Perry', 'Fresno');
INSERT INTO customers VALUES (20, 'Micah Turner', 'Lincoln');
CREATE TABLE products (id INTEGER, name TEXT, price INTEGER);
INSERT INTO products VALUES (1, 'Notebook', 12);
INSERT INTO products VALUES (2, 'Desk Lamp', 34);
INSERT INTO products VALUES (3, 'Travel Mug', 18);
INSERT INTO products VALUES (4, 'Canvas Bag', 26);
INSERT INTO products VALUES (5, 'Wireless Mouse', 42);
INSERT INTO products VALUES (6, 'Keyboard', 58);
INSERT INTO products VALUES (7, 'Monitor Stand', 49);
INSERT INTO products VALUES (8, 'USB Hub', 23);
INSERT INTO products VALUES (9, 'Water Bottle', 21);
INSERT INTO products VALUES (10, 'Headphones', 76);
INSERT INTO products VALUES (11, 'Phone Holder', 16);
INSERT INTO products VALUES (12, 'Power Adapter', 31);
INSERT INTO products VALUES (13, 'Reading Light', 28);
INSERT INTO products VALUES (14, 'Storage Box', 19);
INSERT INTO products VALUES (15, 'Laptop Sleeve', 37);
INSERT INTO products VALUES (16, 'Pen Set', 14);
INSERT INTO products VALUES (17, 'Desk Mat', 29);
INSERT INTO products VALUES (18, 'Cable Kit', 11);
INSERT INTO products VALUES (19, 'Portable Speaker', 64);
INSERT INTO products VALUES (20, 'Planner', 17);
CREATE TABLE events (id INTEGER, level TEXT, message TEXT);
INSERT INTO events VALUES (1, 'INFO', 'Pager test event 001: storage snapshot created with a long message to add realistic payload bytes across the database file.');
INSERT INTO events VALUES (2, 'WARN', 'Pager test event 002: a page boundary may be crossed while saving this record, so verify all content after reloading.');
INSERT INTO events VALUES (3, 'INFO', 'Pager test event 003: this event is deliberately verbose to make the serialized rows span multiple fixed-size storage pages.');
INSERT INTO events VALUES (4, 'DEBUG', 'Pager test event 004: the page header records the current page count while the body contains serialized table data.');
INSERT INTO events VALUES (5, 'INFO', 'Pager test event 005: repeated inserts force Storage to save larger snapshots and exercise page allocation repeatedly.');
INSERT INTO events VALUES (6, 'WARN', 'Pager test event 006: confirm that reading the final rows works even when earlier records occupy several pages.');
INSERT INTO events VALUES (7, 'INFO', 'Pager test event 007: each message includes enough descriptive text to create a useful multi-page manual test database.');
INSERT INTO events VALUES (8, 'DEBUG', 'Pager test event 008: allocated pages should be zero-filled before payload bytes are written into their page slots.');
INSERT INTO events VALUES (9, 'INFO', 'Pager test event 009: this sample gives the database repeated realistic data instead of a single oversized record.');
INSERT INTO events VALUES (10, 'WARN', 'Pager test event 010: check that page reads return complete pages and that padding bytes do not leak into values.');
INSERT INTO events VALUES (11, 'INFO', 'Pager test event 011: the storage file should now be larger than one header page after these inserts are saved.');
INSERT INTO events VALUES (12, 'DEBUG', 'Pager test event 012: several rows are intentionally present so page count can grow as the database snapshot grows.');
INSERT INTO events VALUES (13, 'INFO', 'Pager test event 013: reload this database in a new engine instance and compare the final selected records.');
INSERT INTO events VALUES (14, 'WARN', 'Pager test event 014: the long payload makes page spanning easy to observe in the binary database file.');
INSERT INTO events VALUES (15, 'INFO', 'Pager test event 015: table metadata and row data share the serialized payload distributed across allocated pages.');
INSERT INTO events VALUES (16, 'DEBUG', 'Pager test event 016: every page is fixed width even when its final payload fragment contains fewer bytes.');
INSERT INTO events VALUES (17, 'INFO', 'Pager test event 017: use this entry to verify values remain intact after page padding is stripped on database load.');
INSERT INTO events VALUES (18, 'WARN', 'Pager test event 018: the test database includes multiple tables as well as many rows in the events table.');
INSERT INTO events VALUES (19, 'INFO', 'Pager test event 019: snapshots grow with each saved command and should continue to occupy multiple pages.');
INSERT INTO events VALUES (20, 'DEBUG', 'Pager test event 020: page allocation appends space while the header is updated with the new total page count.');
INSERT INTO events VALUES (21, 'INFO', 'Pager test event 021: a healthy storage round trip should preserve every character in this explanatory message.');
INSERT INTO events VALUES (22, 'WARN', 'Pager test event 022: inspect the page count in the header and confirm it matches the physical file length.');
INSERT INTO events VALUES (23, 'INFO', 'Pager test event 023: the final query below selects later records to make the manual output easy to inspect.');
INSERT INTO events VALUES (24, 'DEBUG', 'Pager test event 024: this row adds more data near the end of the serialized snapshot for boundary coverage.');
INSERT INTO events VALUES (25, 'INFO', 'Pager test event 025: multiple pages are expected because all three tables and their rows are persisted together.');
INSERT INTO events VALUES (26, 'WARN', 'Pager test event 026: verify this message appears exactly as written after the pager reads the database snapshot.');
INSERT INTO events VALUES (27, 'INFO', 'Pager test event 027: a selected result should contain only rows matching the requested identifier condition.');
INSERT INTO events VALUES (28, 'DEBUG', 'Pager test event 028: the database should remain readable after closing and reopening its pager-backed storage.');
INSERT INTO events VALUES (29, 'INFO', 'Pager test event 029: near-final sample payload keeps the persisted file large enough for page inspection.');
INSERT INTO events VALUES (30, 'WARN', 'Pager test event 030: this final stored event is selected by the SQL statement at the end of the script.');
SELECT * FROM events WHERE id > 25;
